In [1]:
import torch as torch
from einops import rearrange, einsum

In [2]:
matrix = torch.zeros(5, 5)
std = 3
torch.nn.init.trunc_normal_(tensor=matrix, mean= 0, std=std, a=-1*std, b=1*std)

tensor([[ 1.4812, -2.6589, -0.6323, -0.5299,  2.2905],
        [-2.4060, -0.7331, -0.3381, -1.8771,  2.4229],
        [-2.2329, -2.4598,  1.8162, -2.0080,  0.8597],
        [-0.7264, -0.6884, -0.1968, -2.0172,  1.5486],
        [ 2.4393,  2.0981,  1.9073, -0.8442,  0.6080]])

In [3]:
list_ids = torch.Tensor([[1, 4, 6, 8], [2, 4, 6, 7]])
matrix[list_ids.long]

IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got builtin_function_or_method)

In [104]:
rmsNorm = torch.sqrt(torch.mean(matrix**2, dim=-1, keepdim=True))
rmsNorm
g = torch.ones(5) * 2
g

tensor([2., 2., 2., 2., 2.])

In [105]:
(matrix / rmsNorm ) * g

tensor([[-1.3609, -1.6449, -0.4233,  3.8051, -0.8857],
        [ 3.3412,  0.1448, -0.9739, -0.0451, -2.8044],
        [-0.5215, -0.3161,  0.1797,  3.0257,  3.2312],
        [ 0.9882,  0.2900, -2.9197, -1.5486,  2.8314],
        [ 1.6589,  2.1460, -1.8879,  1.3226,  2.7073]])

In [107]:
matrix

tensor([[-0.9455, -1.1428, -0.2941,  2.6435, -0.6153],
        [ 2.7207,  0.1179, -0.7930, -0.0367, -2.2836],
        [-0.4255, -0.2579,  0.1466,  2.4685,  2.6361],
        [ 0.8475,  0.2487, -2.5041, -1.3282,  2.4284],
        [ 1.7099,  2.2120, -1.9459,  1.3633,  2.7906]])

In [111]:
torch.exp(matrix) / torch.sum(torch.exp(matrix), dim= -1, keepdim=True)

tensor([[0.0242, 0.0199, 0.0464, 0.8759, 0.0337],
        [0.8518, 0.0631, 0.0254, 0.0541, 0.0057],
        [0.0231, 0.0273, 0.0408, 0.4164, 0.4924],
        [0.1525, 0.0838, 0.0053, 0.0173, 0.7410],
        [0.1579, 0.2609, 0.0041, 0.1117, 0.4654]])

In [116]:
matrix - torch.amax(matrix, dim=-1, keepdim=True)

tensor([[-3.5890, -3.7863, -2.9376,  0.0000, -3.2588],
        [ 0.0000, -2.6028, -3.5137, -2.7574, -5.0044],
        [-3.0615, -2.8939, -2.4894, -0.1676,  0.0000],
        [-1.5808, -2.1797, -4.9325, -3.7566,  0.0000],
        [-1.0807, -0.5786, -4.7365, -1.4273,  0.0000]])

In [ ]:
mask = torch.tril(torch.ones_like(torch.Tensor(3,3), dtype=torch.bool), diagonal=0) 

In [ ]:
d_k = 6
theta = torch.pi/10

# Compute frequencies (correct formula)
k = torch.arange(0, d_k // 2)
freqs = 1.0 / (theta ** (2 * k / d_k))  # (d_k/2,)

positions = torch.arange(4).unsqueeze(1)  # (L, 1)

# Outer product → angles
angles = positions * freqs  # (L, d_k/2)


In [12]:
angles

tensor([[0.0000, 0.0000, 0.0000],
        [1.0000, 1.4710, 2.1639],
        [2.0000, 2.9420, 4.3278],
        [3.0000, 4.4130, 6.4916]])

In [13]:
matrix

tensor([[ 1.4812, -2.6589, -0.6323, -0.5299,  2.2905],
        [-2.4060, -0.7331, -0.3381, -1.8771,  2.4229],
        [-2.2329, -2.4598,  1.8162, -2.0080,  0.8597],
        [-0.7264, -0.6884, -0.1968, -2.0172,  1.5486],
        [ 2.4393,  2.0981,  1.9073, -0.8442,  0.6080]])

In [21]:
rand = torch.rand(3, 3, 4)
rand

tensor([[[8.6967e-01, 7.9703e-01, 8.5888e-01, 5.0544e-01],
         [2.7112e-01, 3.8762e-01, 9.2051e-02, 4.2402e-02],
         [9.1618e-04, 7.5353e-01, 2.2616e-01, 4.1215e-01]],

        [[6.2653e-01, 5.9181e-01, 4.0415e-01, 1.7620e-01],
         [1.9049e-01, 4.7932e-01, 3.1577e-01, 9.6327e-01],
         [7.1625e-02, 6.3948e-01, 4.5019e-01, 8.0531e-01]],

        [[1.7161e-01, 4.8912e-01, 5.7784e-01, 1.3950e-01],
         [1.6292e-01, 3.9598e-01, 4.2343e-01, 9.8166e-01],
         [8.7900e-02, 7.7047e-01, 5.3325e-01, 3.8067e-01]]])

In [23]:
torch.arange(rand.shape[-2])

tensor([0, 1, 2])

In [13]:
from language_model import transformer_block
import torch as torch

layers = torch.nn.ModuleList(transformer_block(d_model=4, num_heads=4, d_ff=10, 
                                               max_seq_len=10, theta=torch.pi) for _ in range(3))

layers[0]

transformer_block(
  (attn): multihead_self_attention_with_RoPE(
    (q_proj): Linear()
    (k_proj): Linear()
    (v_proj): Linear()
    (output_proj): Linear()
    (rope): RoPE()
  )
  (ffn): Positionwise_feedforward(
    (w1): Linear()
    (w2): Linear()
    (w3): Linear()
  )
  (ln1): RMSNorm()
  (ln2): RMSNorm()
)

In [14]:
layers.state_dict().keys()

odict_keys(['0.attn.q_proj.weight', '0.attn.k_proj.weight', '0.attn.v_proj.weight', '0.attn.output_proj.weight', '0.attn.rope.cos_tensor', '0.attn.rope.sin_tensor', '0.ffn.w1.weight', '0.ffn.w2.weight', '0.ffn.w3.weight', '0.ln1.weight', '0.ln2.weight', '1.attn.q_proj.weight', '1.attn.k_proj.weight', '1.attn.v_proj.weight', '1.attn.output_proj.weight', '1.attn.rope.cos_tensor', '1.attn.rope.sin_tensor', '1.ffn.w1.weight', '1.ffn.w2.weight', '1.ffn.w3.weight', '1.ln1.weight', '1.ln2.weight', '2.attn.q_proj.weight', '2.attn.k_proj.weight', '2.attn.v_proj.weight', '2.attn.output_proj.weight', '2.attn.rope.cos_tensor', '2.attn.rope.sin_tensor', '2.ffn.w1.weight', '2.ffn.w2.weight', '2.ffn.w3.weight', '2.ln1.weight', '2.ln2.weight'])

In [61]:
inputs = torch.randn(10, 6)  # [batch_size, vocab_size]
targets = torch.randint(0, 5, (1, 10)).squeeze()  # [batch_size, ]

In [80]:
inputs

tensor([[-0.4202, -2.7797,  0.2624, -0.1673,  0.2516,  0.9473],
        [-0.2564, -0.0730, -2.0864, -0.5506,  0.3975,  0.2469],
        [-0.1198,  1.7143, -0.4368, -0.4280, -0.9173,  1.9687],
        [-0.5251, -1.3667,  0.5154, -0.7710, -1.8710, -2.1319],
        [ 0.3730,  0.6136, -0.9074, -1.3994,  0.5898, -0.3081],
        [-0.3563,  3.3080, -1.8940,  0.0222, -1.1687, -1.4231],
        [ 0.4293, -0.2792,  0.4757, -0.2400, -0.6147,  0.7356],
        [ 1.1072,  0.8507,  1.1909, -1.7169,  0.0786, -0.0171],
        [-1.4612, -0.6395, -1.8137,  0.7979,  0.5697, -2.3914],
        [ 0.3916, -0.3515, -0.1331, -0.0453, -0.9474,  0.1468]])

In [82]:
torch.amax(inputs, dim = -1, keepdim=True)

tensor([[0.9473],
        [0.3975],
        [1.9687],
        [0.5154],
        [0.6136],
        [3.3080],
        [0.7356],
        [1.1909],
        [0.7979],
        [0.3916]])

In [65]:
targets = targets.view(-1, 1)
targets

tensor([[2],
        [1],
        [2],
        [3],
        [3],
        [0],
        [1],
        [3],
        [3],
        [2]])

In [78]:
inputs.gather(1, targets).squeeze()

tensor([ 0.2624, -0.0730, -0.4368, -0.7710, -1.3994, -0.3563, -0.2792, -1.7169,
         0.7979, -0.1331])

In [74]:
torch.exp(inputs)

tensor([[ 0.6569,  0.0621,  1.3000,  0.8460,  1.2861,  2.5787],
        [ 0.7738,  0.9296,  0.1241,  0.5766,  1.4881,  1.2801],
        [ 0.8871,  5.5527,  0.6461,  0.6518,  0.3996,  7.1616],
        [ 0.5915,  0.2550,  1.6743,  0.4626,  0.1540,  0.1186],
        [ 1.4521,  1.8471,  0.4036,  0.2467,  1.8036,  0.7348],
        [ 0.7002, 27.3293,  0.1505,  1.0224,  0.3108,  0.2410],
        [ 1.5362,  0.7564,  1.6091,  0.7866,  0.5408,  2.0867],
        [ 3.0259,  2.3412,  3.2901,  0.1796,  1.0818,  0.9831],
        [ 0.2320,  0.5276,  0.1631,  2.2208,  1.7677,  0.0915],
        [ 1.4793,  0.7036,  0.8754,  0.9557,  0.3877,  1.1581]])

In [76]:
torch.log(torch.sum(torch.exp(inputs), dim=-1))

tensor([1.9065, 1.6433, 2.7278, 1.1805, 1.8699, 3.3930, 1.9900, 2.3889, 1.6099,
        1.7156])

In [44]:
# Reshape indices to (3, 1) to match data dimensions
col_indices = torch.tensor([2, 0, 1]).view(-1, 1)

# dim=1 means we are gathering along the columns
result = inputs.gather(1, col_indices)
print(result) # tensor([[30], [40], [80]])

tensor([[-0.8836],
        [-0.1758],
        [-0.0929]])


In [127]:
import numpy as np
dataset = np.arange(0, 100)

batch_size = 5
context_length = 10 
start_indexs = np.random.randint(0, 100 - context_length, size = batch_size).reshape(-1, 1)

out = []
# for start_index in start_indexs:
#     ids = dataset[start_index: start_index + context_length]
#     out.append(ids)

# out = np.array(out)

In [128]:
dataset

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [129]:
start_indexs

array([[60],
       [68],
       [25],
       [69],
       [16]])

In [119]:
dataset[start_indexs]

array([84,  8, 23, 20, 27])

In [114]:
torch.Tensor(np.array(out))

tensor([[84., 85., 86., 87., 88., 89., 90., 91., 92., 93.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
        [23., 24., 25., 26., 27., 28., 29., 30., 31., 32.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [27., 28., 29., 30., 31., 32., 33., 34., 35., 36.]])

In [130]:
# 1. Define starting values (n) for each row
n_values = np.array([0, 10, 20])

# 2. Reshape to a column vector (m x 1)
n_col = n_values.reshape(-1, 1)

# 3. Create offsets from 0 to 10
offsets = np.arange(11)

# 4. Use broadcasting to create the 2D array
array_2d = n_col + offsets

print(array_2d)

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [10 11 12 13 14 15 16 17 18 19 20]
 [20 21 22 23 24 25 26 27 28 29 30]]


In [132]:
array_2d + 1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [133]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [134]:
dataset[array_2d]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])